multiSensorFusion_slam:
  config_file: "/home/lwh/code/lwh_ws-master/src/liv_slam-master/config/MultiSensorSystem/multi_system.yaml"
  lidar_num: 1
  lidar:
    type: "rotary"     # "livox_Horizon"    
    topic:
      index_0: "/left/velodyne_points"       #  "/points_raw"     /rslidar_points     /left/velodyne_points
      index_1: "/right/velodyne_points"
    scan: 16
    scan_period: 0.1
