multiSensorFusion_slam:
  config_file: "/home/lwh/code/lwh_ws-master/src/liv_slam-master/config/MultiLidar_system/loam_feature_multi_lidar_system.yaml"
  lidar_num: 2
  lidar:
    topic:
      index_0: "/left/velodyne_points"       #  "/points_raw" 
      index_1: "/right/velodyne_points"
    scan: 16
    scan_period: 0.1
